services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kusafe-frontend:local
    container_name: kusafe-frontend-local
    restart: unless-stopped
    ports:
      - "5549:80"
